"""updates to various tables

Revision ID: b44b2524d9e3
Revises: f231169e000e
Create Date: 2018-08-11 22:40:06.358169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44b2524d9e3'
down_revision = 'f231169e000e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('abbreviation', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('email_address', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_created_ts'), 'station', ['created_ts'], unique=False)
    op.create_index(op.f('ix_station_name'), 'station', ['name'], unique=False)
    op.add_column('department', sa.Column('email_address', sa.String(length=128), nullable=True))
    op.add_column('department', sa.Column('fd_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_department_fd_id'), 'department', ['fd_id'], unique=False)
    op.add_column('equipment', sa.Column('capital_equipment', sa.String(length=128), nullable=True))
    op.add_column('equipment', sa.Column('description', sa.String(length=512), nullable=True))
    op.add_column('equipment', sa.Column('serial_number', sa.String(length=128), nullable=True))
    op.add_column('equipment_check_log', sa.Column('notes', sa.String(length=512), nullable=True))
    op.add_column('truck', sa.Column('contact_ts', sa.DateTime(), nullable=True))
    op.add_column('truck', sa.Column('position_address', sa.String(length=256), nullable=True))
    op.add_column('truck', sa.Column('position_ts', sa.DateTime(), nullable=True))
    op.add_column('truck', sa.Column('radio_id', sa.String(length=128), nullable=True))
    op.add_column('truck', sa.Column('station_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_truck_contact_ts'), 'truck', ['contact_ts'], unique=False)
    op.create_index(op.f('ix_truck_position_ts'), 'truck', ['position_ts'], unique=False)
    op.create_index(op.f('ix_truck_radio_id'), 'truck', ['radio_id'], unique=False)
    op.drop_constraint(None, 'truck', type_='foreignkey')
    op.create_foreign_key(None, 'truck', 'station', ['station_id'], ['id'])
    op.drop_column('truck', 'department_id')
    op.drop_column('truck', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('truck', sa.Column('address', sa.VARCHAR(length=256), nullable=True))
    op.add_column('truck', sa.Column('department_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'truck', type_='foreignkey')
    op.create_foreign_key(None, 'truck', 'department', ['department_id'], ['id'])
    op.drop_index(op.f('ix_truck_radio_id'), table_name='truck')
    op.drop_index(op.f('ix_truck_position_ts'), table_name='truck')
    op.drop_index(op.f('ix_truck_contact_ts'), table_name='truck')
    op.drop_column('truck', 'station_id')
    op.drop_column('truck', 'radio_id')
    op.drop_column('truck', 'position_ts')
    op.drop_column('truck', 'position_address')
    op.drop_column('truck', 'contact_ts')
    op.drop_column('equipment_check_log', 'notes')
    op.drop_column('equipment', 'serial_number')
    op.drop_column('equipment', 'description')
    op.drop_column('equipment', 'capital_equipment')
    op.drop_index(op.f('ix_department_fd_id'), table_name='department')
    op.drop_column('department', 'fd_id')
    op.drop_column('department', 'email_address')
    op.drop_index(op.f('ix_station_name'), table_name='station')
    op.drop_index(op.f('ix_station_created_ts'), table_name='station')
    op.drop_table('station')
    # ### end Alembic commands ###
