"""created equipment log

Revision ID: f231169e000e
Revises: 757dd9a0edba
Create Date: 2018-08-11 13:23:54.836743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f231169e000e'
down_revision = '757dd9a0edba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_check_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('MISSING', 'PRESENT', 'DAMAGED', name='equipmentstatus'), nullable=True),
    sa.Column('compartment_id', sa.Integer(), nullable=True),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_check_log_created_ts'), 'equipment_check_log', ['created_ts'], unique=False)
    op.add_column('equipment', sa.Column('last_checked_ts', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_equipment_last_checked_ts'), 'equipment', ['last_checked_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_equipment_last_checked_ts'), table_name='equipment')
    op.drop_column('equipment', 'last_checked_ts')
    op.drop_index(op.f('ix_equipment_check_log_created_ts'), table_name='equipment_check_log')
    op.drop_table('equipment_check_log')
    # ### end Alembic commands ###
